### ISSUE TITLE
How to control to MEMORY used by PROST

### ISSUE THREAD

**Issue by cchd0001** [Tang-Lab-super/PROST#2]
Hi， 

Thanks for developing this useful package.

Here is my issue: I got an data of 133,350 cells with 20,000 genes . In an machine with 500GB memory I run the PROST function but failed by "Unable to allocate"
![image](https://github.com/Tang-Lab-super/PROST/assets/8720584/ba967034-7758-420c-b9d7-64ba6094baa1)

Is there anyway to limit the memory cost of PROST ？
Or how many memory should I prepare for this dateset ?

Thanks
Lidong GUo

**Comment by Sicrve11** [comment]
Thanks very much for your feedback about memory usage, this is one of our shortcomings as we use an adjacency matrix approach when building graph neural networks, which results in slower runs and heavier memory burden on larger datasets. We might improve it at a later stage by using sparse matrices or by using DGL.

I see that you are using the function **spatial_autocorrelation**, you may be able to mitigate this by reducing the size of the  **permutations**.
