### ISSUE TITLE
如何加入其他空间数据进行分析

### ISSUE THREAD

**Issue by JWJ13164328557** [Tang-Lab-super/PROST#5]
我加入了我们自己的空间数据，添加了空间位置信息进去，保存成loom后转成h5ad格式导入流程，但报错
>>> rootdir = '/data/liux/quanxibaohebingchulijiaoben/julei/ZCL/BSTViewer_project/jz/S_T1_1___all/SCT_C10_F50_P30_R0.5'
>>> input_dir = os.path.join(rootdir)
>>> output_dir = os.path.join(rootdir, 'results/')
>>> adata=sc.read(input_dir+"/object.h5ad")
>>> adata = PROST.prepare_for_PI(adata, percentage = 0.01, platform="/data/liux/quanxibaohebingchulijiaoben/julei/ZCL/BSTViewer_project/jz/S_T1_1___all/SCT_C10_F50_P30_R0.5")

Filtering genes ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liux/miniconda3/envs/BMCstereoseq/PROST-1.1.2/PROST/calculate_PI.py", line 29, in prepare_for_PI
    locates = adata.obsm["spatial"].astype(float)
  File "/home/liux/miniconda3/envs/Genomic/lib/python3.9/site-packages/anndata/_core/aligned_mapping.py", line 196, in __getitem__
    return self._data[key]
KeyError: 'spatial'
添加空间位置信息如下：
AnnData object with n_obs × n_vars = 18367 × 34140
    obs: 'Row.names', 'SCT_snn_res.0.5', 'nCount_RNA', 'nCount_SCT', 'nFeature_RNA', 'nFeature_SCT', 'orig.ident', 'pos_h', 'pos_w', 'seurat_clusters'
    layers: 'counts'

**Comment by Sicrve11** [comment]
数据格式的问题，空间位置信息需要加到adata.obsm["spatial"]字段下面，可以根据你的空转平台去参考对应的示例数据。
