### ISSUE TITLE
PROST not compatible with Visium HD data (single-cell resolution of ST data) - Memory Error - Over 600k bins/spots

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [Tang-Lab-super/PROST#8]
Hey, just like many other tools, I'm trying to run PROST and it gives a memory error (actually, it simply kills the terminal) using Visium HD data (600k bins/spots)

Dataset can be found here https://www.10xgenomics.com/datasets?query=&page=1&configure%5BhitsPerPage%5D=50&configure%5BmaxValuesPerFacet%5D=1000 and is the Lung cancer visium HD dataset

>>> adata = PROST.prepare_for_PI(adata, platform="visium")

Killed

Adata shape:

AnnData object with n_obs × n_vars = 605471 × 18085
obs: 'in_tissue', 'array_row', 'array_col'
var: 'gene_ids', 'feature_types', 'genome'
uns: 'spatial'
obsm: 'spatial'

Unfortunately, it doesn't seem to be compatible with high resolution spatial data

Thanks

**Comment by Sicrve11** [comment]
Thank you for your feedback on Visium HD data usage. We are trying to improve the memory complexity of the model to accommodate the latest spatial transcriptome sequencing platform technologies. Thank you very much for providing the sample data, we will prioritize the use of this data for testing, and update it when the test is completed, thank you for your attention!
